version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: chat_app_database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - chat_app_database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

volumes:
  chat_app_database: